### ISSUE TITLE
Problems with alsaseqio linking during build

### ISSUE THREAD

**Issue by huddx01** [michaelforney/oscmix#3] opened 2024-02-18 02:40 UTC
Hi Michael,

First, i would like to say, really great work!
Seems to have the potential to support the capabilities of Totalmix on most of the RME units on linux. 

I was able to build oscmix and alsarawio on a rpi v3.

But I have problems with alsaseqio.

Any hints?

Thanks in advance, meg

```
make
cc -std=c11 -O1   -c -o main.o main.c
cc -std=c11 -O1   -c -o osc.o osc.c
cc -std=c11 -O1   -c -o oscmix.o oscmix.c
cc -std=c11 -O1   -c -o socket.o socket.c
cc -std=c11 -O1   -c -o sysex.o sysex.c
cc -std=c11 -O1   -c -o util.o util.c
cc -std=c11  -o oscmix main.o osc.o oscmix.o socket.o sysex.o util.o -l pthread -l m
cc -std=c11 -O1   -c -o alsarawio.o alsarawio.c
cc -std=c11  -o alsarawio alsarawio.o
cc -std=c11  -O1 $(pkg-config --cflags alsa) -c -o alsaseqio.o alsaseqio.c
cc -std=c11  $(pkg-config --libs-only-L --libs-only-other alsa) -o alsaseqio alsaseqio.o $(pkg-config --libs-only-l alsa)
/usr/bin/ld: alsaseqio.o: undefined reference to symbol 'pthread_create@@GLIBC_2.4'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:66: alsaseqio] Fehler 1

```

**Comment by michaelforney** [comment] 2024-02-18 02:55
Thanks for the report. The issue is that `alsaseqio` needs `-l pthread`. I didn't notice this since I typically use a linux system with musl libc, which has pthread built into libc. But I do have a continuous build set up for Debian, which didn't catch it either (maybe it was getting it from libasound?)

Anyway, this should be fixed now. Let me know if you encounter any other build issues.

**Closed** 2024-02-18 02:54 UTC

**Comment by michaelforney** [comment] 2024-02-18 05:50
Yes, this error means you are missing the gtk3 development package. Your best bet is to search your operating system's package repository for the package name and install it. I'd expect `libgtk-3-dev` to work on a Debian-based system. It's only necessary if you want to use the gtk UI.

If you don't care about the gtk UI, you can build with `make GTK=n` or create a file `config.mk` containing `GTK=n`.

**Comment by michaelforney** [comment] 2024-02-19 01:45
Ugh, that's annoying. It seems that it might need a newer glib. I will investigate this later. For now, you can just disable gtk in `config.mk`.
